ignore:
  - "mp2p_icp_core/3rdparty/"
  - "mp2p_icp_core/apps/"
  - "mp2p_icp_core/demos/"
  - "mp2p_icp_core/tests/"
  - "mp2p_icp_viz/apps/"

# Pull Request Comment Configuration (Optional)
# This controls the comment that Codecov posts on your pull requests.
comment:
  layout: "reach, diff, files"
  behavior: default # "default" will update an existing comment or post a new one.
  require_changes: false # Post a comment even if coverage did not change.
